export const FETCH_PRODUCTOS = "FETCH_PRODUCTOS";
export const FETCH_PRODUCTO = "FETCH_PRODUCTO";
export const FETCH_MARCAS = "FETCH_MARCAS";
export const FETCH_CATEGORIAS = "FETCH_CATEGORIAS";
export const FETCH_SUBCATEGORIAS = "FETCH_SUBCATEGORIAS";
