export const FETCH_PRODUCTOS = "FETCH_PRODUCTOS";
export const FETCH_PRODUCTO = "FETCH_PRODUCTO";
export const ADD_PRODUCTO = "ADD_PRODUCTO";
export const FETCH_MARCAS = "FETCH_MARCAS";
export const ADD_MARCA = "ADD_MARCA";
export const FETCH_CATEGORIAS = "FETCH_CATEGORIAS";
export const ADD_CATEGORIA = "ADD_CATEGORIA";
export const FETCH_SUBCATEGORIAS = "FETCH_SUBCATEGORIAS";
